# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  title: Bargain Bee API
  description: Move your app forward with the Bargain API
  version: "1.0.0"
# will be prefixed to all paths
basePath: /v1
# Describe your paths here
# This is a path endpoint. Change it.
paths:
  /campaigns:
    get:
      summary: All campaigns
      description: |
        Returns all campaigns that were entered the system
      tags:
        - Campaigns
      responses:
        200:
          description: An array of campaigns
          schema:
            type: array
            items:
              $ref: '#/definitions/Campaign'
    post:
      summary: Add a new campaign 
      description: ""
      tags:
        - Campaigns
      parameters:
        - in: body
          name: body
          description: Campaign object that needs to be added 
          required: true
          schema:
            $ref: "#/definitions/Campaign"
      responses:
        "405":
          description: Invalid input
  /users:
    get:
      summary: All Users
      description: |
        Returns all users in the system
      tags:
        - Users
      responses:
        200:
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Add a new user 
      description: ""
      tags:
        - Users
      parameters:
        - in: body
          name: body
          description: User object that needs to be added 
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "405":
          description: Invalid input
  /users/{roleId}:
    get:
      summary: Users by a specific role
      description: |
        Returns all users in the system with the roleId specified
      parameters:
      - in: path
        name: roleId
        description: Id of role you want to sort users by
        required: true
        type: integer
        format: int16
        default: 1
        minimum: 1
        maximum: 3
      responses:
        200:
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
  /campaigns/{id}/promotions:
    get:
      summary: Show Campaign Promotions
      description: |
        Returns all Promotions associated with a campaign
      tags:
        - Promotions
      parameters:
        - in: path
          name: id
          description: ID of campaign that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: An array of promotions
          schema:
            type: array
            items:
              $ref: '#/definitions/Promotion'
    post:
      summary: Add a new promotion to the campaign
      description: ""
      tags:
        - Promotions
      parameters:
        - in: path
          name: id
          description: ID of campaign that needs to be fetched
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Promotion object that needs to be added to the specified campaign
          required: true
          schema:
            $ref: "#/definitions/Promotion"
      responses:
        "405":
          description: Invalid input
  /campaigns/{campID}/promotions/{promoID}:
    get:
      summary: Show one Promotion
      description: |
        Returns a Promotion associated with a campaign
      tags:
        - Promotions
      parameters:
        - in: path
          name: campID
          description: ID of campaign that needs to be fetched
          required: true
          type: integer
          format: int64
        - in: path
          name: promoID
          description: ID of promotion that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: returns promotion
          schema:
            $ref: '#/definitions/Promotion'
definitions: 
  User:
    type: object
    properties:
      username: 
        type: string
        description: display name for this user
      role:
        type: array
        items:
          $ref: '#/definitions/Role'
  Role:
    type: object
    properties:
      UUID:
        type: integer
        format: int16
        description: role ID associated with each different role available (1 - 3)
  Campaign:
    type: object
    properties:
      UUID:
        type: integer
        format: int64
      name:
        type: string
        description: campaign name
      promotions:
        type: array
        items:
          $ref: '#/definitions/Promotion'
  Image: 
    type: object
    properties:
      picture:
        type: string
        description: image url
      image_type:
        type: integer
        format: int16
        description: ID relating to what type of image this is--> reference or audit image
  Store:
    type: object
    properties:
      UUID:
        type: integer
        format: int64
        description: store ID
  Single_completion:
    type: object
    properties:
      Store:
        $ref: '#/definitions/Store'
      Completion_Status:
        type: boolean
        description: Identifies if the store completed the promotion
  Promotion:
    type: object
    properties:
      UUID:
        type: integer
        format: int64
      name:
        type: string
        description: promotion name
      start:
        type: string
        format: date-time
        description: the starting date for this promotion
      end: 
        type: string
        format: date-time
        description: the ending date for this promotion
      products:
        type: array
        items:
          type: string
      stores:
        type: array
        items:
          $ref: '#/definitions/Store'
      image:
        $ref: '#/definitions/Image'
      posted:
        type: string
        format: full-date
        description: date promotion was posted
      status:
        type: string
        description: expiry status, shows if the promotion has already ended
      shelf_number:
        type: integer
        format: int32
        description: shelf number to place promotion on
      bin_number:
        type: integer
        description: bin number to place promotion on
      completion_table:
        type: array
        items:
          $ref: '#/definitions/Single_completion'
